version: "3"

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: DBPASSWORD
      POSTGRES_DB: quizit

  pusher:
    image: "quay.io/soketi/soketi:1.4-16-debian"
    environment:
      - SOKETI_DEFAULT_APP_ID=REPLACE_WITH_YOUR_APP_ID
      - SOKETI_DEFAULT_APP_KEY=REPLACE_WITH_YOUR_APP_KEY
      - SOKETI_DEFAULT_APP_SECRET=REPLACE_WITH_YOUR_APP_SECRET
      - SOKETI_DEBUG=1
    ports:
      - "6001:6001"
      - "9601:9601"
